export const ACTION_TYPES = {
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    SET_PROJECTS: 'SET_PROJECTS',
    ADD_PROJECT: 'ADD_PROJECT',
    REMOVE_PROJECT: 'REMOVE_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    SET_PROJECTS_ERROR: 'SET_PROJECTS_ERROR',
    FETCH_PROJECTS_START: 'FETCH_PROJECTS_START',
    SET_TASKS : 'SET_TASKS',
    ADD_TASK: 'ADD_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    FETCH_TASKS_FAILURE:'FETCH_TASKS_FAILURE',
    FETCH_TASKS_START: 'FETCH_TASKS_START',
    TOGGLE_CREATE_MODAL: 'TOGGLE_CREATE_MODAL',
    SET_USER: 'SET_USER'
}